### ISSUE TITLE
we need to send broadcast like messages to all listeners.

### ISSUE THREAD

**Issue by geetee24** [taylorhakes/postmessage-plus#1]
We need to send a message from \* and to *.

or say, locahost to localhost.

PmPlus fails when the 2 domains are the same. With error : "No listener"

Can you help fix this?

Thank you

**Comment by taylorhakes** [comment]
@geetee24 Could you give me more details on the error you are seeing? I just tested postmessage-plus with the same domain and didn't see an issue. If you could use JSBin, JSFiddle or post failing code here, it would make it much easier to debug.

**Comment by geetee24** [comment]
cant post code.

if we send and listen to FOO.com in parent

and in an iframe, also send and listen to FOO

we get message NO LISTENER from pmplus.

Also looking at the source code,  pmplus does not properrly treat '_' as a wilcard. it fails because it compares the received domain (the oringin) to '_' and if does notmatch so it fails.

**Comment by taylorhakes** [comment]
I understand if you can't post your actual code. I tested with the same domain and can't see the issue. Can you post a simple example reproducing the issue? I won't be able to see the issue without some example code.

'' is not meant to be wildcard. postmessage-plus supports regex domains, but should be used sparingly. The library was meant to be security focused. Sending to to all domains was not a use case. Generally `*`, is a very bad idea.

**Comment by taylorhakes** [comment]
Closing until I get more info
